### ISSUE TITLE
archivo version Google doc

### ISSUE THREAD

**Issue by Sebitash** [gcc-cdimatteo/Base-de-Datos-75.15#2]
Te hago una consulta, 
hay archivos que estan de la forma
{"":"WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!","doc_id":"1sbOR_pzVF3keS2BZbClaQr_oJIGJvZf40Ha3SQOMQRI","resource_key":"","email":"cdimatteo@fi.uba.ar"}
pero no se como abrirlos
me podrias explicar ? muchas gracias

**Comment by gcc-cdimatteo** [comment]
no se pueden abrir :/ me enteré un cuatri más tarde que esos documentos no se pueden recuperar así que solo viven en mi memoria ahora mismo 🥲 sorry

de todas formas fíjate que todos los integradores resueltos están pasados a pdf (los resueltos tienen mucho de lo que tenía el resumen).

cuáles archivos estabas tratando de abrir ? quizás te puedo recuperar algunos (los tengo en físico y podría escanearlos)

**Comment by Sebitash** [comment]
na tranqui, porque por ahi encuentro un archivo ahora, y luego otro mas adelante y no te quiero joder
Te agradezco igual tu disposicion y obviamente tu esfuerzo por hacer este semejante material de estas materias
