### ISSUE TITLE
como acceder a resueltos 

### ISSUE THREAD

**Issue by Sebitash** [gcc-cdimatteo/Base-de-Datos-75.15#3]
buenas caro, tengo una duda
no se como entrar a este archivo /Users/cdimatteo/Library/CloudStorage/GoogleDrive-cdimatteo@fi.uba.ar/.shortcut-targets-by-id/1MjTVCSULrmbMUAkXsnRwHZwUFumnKghs/promocionales_bases_de_datos

**Comment by gcc-cdimatteo** [comment]
ni idea qué es ese archivo, creo que quedó en la carpeta por error. no lo reconozco como algo que yo haya hecho o tenga algo valioso... lo voy a sacar inclusive.
